# Generated by Django 4.0.1 on 2022-02-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The setting key.', max_length=64, verbose_name='Key')),
                ('val', models.CharField(help_text='The setting value.', max_length=64, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(editable=False, null=True)),
                ('parent', models.IntegerField(default=0, editable=False)),
                ('username', models.CharField(help_text='The GitHub username.', max_length=64, unique=True, verbose_name='Username')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_parsed', models.DateTimeField(auto_now_add=True, null=True)),
                ('seeded', models.BooleanField(default=False, editable=False)),
                ('auto_added', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Target_User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gf.user')),
                ('remove_following', models.BooleanField(default=True, help_text='Whether to remove a user that follows from the following list.', verbose_name='Remove Following')),
                ('cleanup_days', models.IntegerField(help_text='Automatically purges uses from the following list after this many days.', verbose_name='Cleanup Days')),
                ('token', models.CharField(help_text="GitHub's personal token for authentication.", max_length=128, verbose_name='Personal Token')),
                ('global_user', models.BooleanField(default=False, help_text="If true, this user's token and username will be used for authentication in general.", verbose_name='Global User')),
            ],
        ),
        migrations.CreateModel(
            name='Seeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gf.user')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gf.user')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gf.target_user')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gf.user')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gf.target_user')),
            ],
        ),
    ]
