# Generated by Django 4.0.1 on 2022-02-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gf', '0003_seeder_time_seeded_alter_setting_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='seeded',
            new_name='needs_to_seed',
        ),
        migrations.RemoveField(
            model_name='seeder',
            name='time_seeded',
        ),
    ]
