# Generated by Django 4.0.1 on 2022-02-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gf', '0004_rename_seeded_user_needs_to_seed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target_user',
            options={'verbose_name': 'Target User'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_updated',
        ),
    ]
