# Generated by Django 4.0.1 on 2022-02-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gf', '0006_alter_user_last_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_user',
            name='allow_follow',
            field=models.BooleanField(default=True, help_text='If true, this user will start following parsed users.', verbose_name='Allow Following'),
        ),
        migrations.AddField(
            model_name='target_user',
            name='allow_unfollow',
            field=models.BooleanField(default=True, help_text='If true, the bot will unfollow users for this target user.', verbose_name='Allow Unfollowing'),
        ),
    ]
