# Generated by Django 4.0.1 on 2022-02-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gf', '0007_target_user_allow_follow_target_user_allow_unfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cur_page',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
