# Generated by Django 4.0.1 on 2022-02-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gf', '0009_user_needs_parsing_follower_follower-target-user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gid',
        ),
    ]
